# -*- coding: utf-8 -*-
# configuration file for aws bill procssing version 2

# bill logs
bill_logs:
  s3_bucket:
    bucket_name: edusoft-aws-bill
    log_prefix: 316674983838-aws-billing-detailed-line-items-with-resources-and-tags-ACTS-


# bill processed
bill_processed:
  s3_bucket:
    bucket_name: edusoft-aws-bill-work
    raw_folder: raw/
    raw_prefix: raw-
    trac_folder: trac/
    trac_prefix: trac-
    tag_folder: tags/
    tag_prefix: cost_tags-
    cal_folder: calc/
    cal_prefix: calc-
    stat_folder: stat/
    stat_prefix: stat-

# local directory
directories:
  tmp: tmp
  data: data
  raw: raw
  trac: trac
  tag: tags
  cal: calc
  stat: stat


# lost tag
lost_tag:
  key: "user:Project"
  value: "Shanghai Edu ZTJY"
  group: "专题教育"
  division: "中小学事业部"

# costcenter tags file
cost_tags:
  tags_file: cost_tags.csv
  start_month: 2014-12
  join_key: "user:Project"

bill_columns:
  user_tags:
    #- "user:Bill"
    #- "user:billTag"
    #- "user:Name"
    - "user:Project"
    #- "user:Division"
    #- "user:Customer"
  calc:
    - "index"
    - "InvoiceID"
    - "PayerAccountId"
    - "LinkedAccountId"
    - "RecordId"
    - "ProductName"
    - "RateId"
    - "SubscriptionId"
    - "PricingPlanId"
    - "UsageType"
    - "Operation"
    - "AvailabilityZone"
    - "ReservedInstance"
    - "ItemDescription"
    - "UsageStartDate"
    - "UsageEndDate"
    - "UsageQuantity"
    - "BlendedRate"
    - "BlendedCost"
    - "UnBlendedRate"
    - "UnBlendedCost"
    - "ResourceId"
    - "user:Project"
    - "ProjectGroup"
    - "CostDivision"
    - "InstanceType"
    - "Platform"
    - "AdjustedCost"
    - "TotalCost"
  raw:
    - "InvoiceID"
    - "PayerAccountId"
    - "LinkedAccountId"
    - "RecordId"
    - "ProductName"
    - "RateId"
    - "SubscriptionId"
    - "PricingPlanId"
    - "UsageType"
    - "Operation"
    - "AvailabilityZone"
    - "ReservedInstance"
    - "ItemDescription"
    - "UsageStartDate"
    - "UsageEndDate"
    - "UsageQuantity"
    - "BlendedRate"
    - "BlendedCost"
    - "UnBlendedRate"
    - "UnBlendedCost"
    - "ResourceId"
    - "user:Project"
  calc_read_csv_dtype:
    UsageQuantity: "np.float64"
    BlendedRate: "np.float64"
    BlendedCost: "np.float64"
    UnBlendedRate: "np.float64"
    UnBlendedCost: "np.float64"

# statistics file
statistics:
  merge_file: history_bill.csv

